services:
    oauth2_server.token_type.bearer:
        class: OAuth2Framework\Component\BearerTokenType\BearerToken
        arguments:
            - '%oauth2_server.token_type.bearer_token.realm%'
            - '%oauth2_server.token_type.bearer_token.authorization_header%'
            - '%oauth2_server.token_type.bearer_token.request_body%'
            - '%oauth2_server.token_type.bearer_token.query_string%'
        tags:
            - { name: oauth2_server_token_type, scheme: 'Bearer' }

    oauth2_server.token_type.mac:
        class: OAuth2Framework\ServerBundle\TokenType\MacToken
        arguments:
            - '%oauth2_server.token_type.mac_token.algorithm%'
            - '%oauth2_server.token_type.mac_token.timestamp_lifetime%'
            - '%oauth2_server.token_type.mac_token.min_length%'
            - '%oauth2_server.token_type.mac_token.max_length%'
        tags:
            - { name: oauth2_server_token_type, scheme: 'plain' }

    oauth2_server.token_type.manager:
        class: OAuth2Framework\Component\TokenType\TokenTypeManager

    oauth2_server.token_type.middleware:
        class: OAuth2Framework\Component\TokenType\TokenTypeMiddleware
        arguments:
            - '@oauth2_server.token_type.manager'
            - '%oauth2_server.token_type.allow_token_type_parameter%'

    oauth2_server.token_type.parameter_checker:
        class: OAuth2Framework\Component\TokenType\TokenTypeMiddleware
        arguments:
            - '@oauth2_server.token_type.manager'
            - '%oauth2_server.token_type.allow_token_type_parameter%'